### ISSUE TITLE
"Firefox Can’t Open This Page" When trying to watch content from membed1 (Canada/Netherlands/etc)

### ISSUE THREAD

**Issue by KELP1234** [ayunami2000/Filmic#2]
When I try to watch something from membed1 (I've tried 2 videos) I get the following error:

Firefox Can’t Open This Page

To protect your security, storage05.fmovcdn.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
[Learn more…](https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct)

![image](https://user-images.githubusercontent.com/31633552/227402673-ae8e91bd-4aeb-4924-896d-362f07de40bd.png)

**Comment by ayunami2000** [comment]
It works for me, maybe try a VPN?

**Comment by KELP1234** [comment]
I tried a few things (VPN and different browser). Under chrome and edge they just gave a "Refused to connect". When I tried a VPN (USA/Netherlands) the US VPN worked and the dutch one didn't.

**Comment by ayunami2000** [comment]
I've added a footnote on the website to use a US VPN if it does not work. The only other alternative is to use some web proxy and proxy all the requests, but I'd rather not send this sort of stuff over my own servers or over anyone else's proxy servers. If you want to, you can self host it locally and see if it works with the server itself running in the same region.
